### PR TITLE
Extended version that can handle full line of text image

### PR DESCRIPTION
**Pull request by lamhoangtung**
I created an extended version of this project that can handle full line of text image. Can you create a new branch on your repo for this version ? I think it will be helpful for a lot of people

Thanks for the great works, Harald 😍

### CODE REVIEW

**Comment by githubharald** [comment]
Hi,

thanks for you work.
However, I want to keep the SimpleHTR repository as simple and small as possible and therefore stick with recognizing at most 32 chars and I also don't want some features hidden in some special branch.
Nevertheless, I think it is a great idea to make your changes public, which will help others who need line-level recognition. If you want I can link from my repository to your repository such that others know about your implementation. You can then put everything into your master branch such that it is easy to see for everyone when looking at your repository at GitHub.

Best, Harald

**Comment by lamhoangtung** [comment]
Thanks you, Harald.

I renamed my fork to **LineHTR:**  https://github.com/lamhoangtung/LineHTR and put everything on the `master` branch.

It would be great if you can drop a link to my repository in the README file of your `SimpleHTR` repository, so that other people can check it out when they need line-level recognition.

Best regraded,
Lam.

**Comment by githubharald** [comment]
thank you. I'll add the link in the next few days.

**Comment by githubharald** [comment]
added the link (section "Improve accuracy" and "FAQ").

**Pull request closed without merging**
